### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by leopoldomt** [LeonardoGaldino/if1001-FastPicture#2]
Seria possível associar à informação da sala criada a localização e assim exibir apenas salas próximas ao local atual do usuário? 

De onde virão as palavras-chave para os objetos? 

@LeonardoGaldino

**Comment by LeonardoGaldino** [comment]
Sim, vamos adicionar essa ideia da localizaçao. 

E sobre as palavras-chave: a priori pensamos em selecionar um conjunto de objetos que a API detecta muito bem e que tambem seja relativamente comum de se ter por perto.

**Comment by leopoldomt** [comment]
Beleza, @LeonardoGaldino. É razoável focar nos objetos que a API funciona bem.
